spring:
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 3600
      password:
  application:
    name: ai-platform
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 123456
server:
  port: 8123
  servlet:
    context-path: /api
# knife4j的增强配置
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        group-name: 接口文档
        api-rule: package
        api-rule-resources:
          - com.itflower.aiplatform.controller
# openapi 配置
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: deepseek-chat
      base-url: https://api.deepseek.com
      strict-json-schema: true
      response-format: json
      max-tokens: 8192
      log-requests: true
      log-responses: true
    streaming-chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: deepseek-chat
      base-url: https://api.deepseek.com
      max-tokens: 8192
      log-requests: true
      log-responses: true
cos:
  bucket: ${TENCENT_COS_BUCKET}
  region: ${TENCENT_COS_REGION:}
  secretId: ${TENCENT_SECRET_ID}
  secretKey: ${TENCENT_SECRET_KEY}
pexels:
  api-key: ${PEXELS_API_KEY}

aliyun:
  api-key: ${ALIYUN_API_KEY}
  model: ${ALIYUN_MODEL}